### ISSUE TITLE
Can't load config.ini

### ISSUE THREAD

**Issue by rambit** [jpcima/fmcomposer#2]
Config doesn't seem to load or save on Linux.

A quick fix was to remove pathSeparator from [configEditor.cpp](https://github.com/jpcima/fmcomposer/blob/master/src/views/settings/configEditor.cpp#L515) but probably not a cross platform solution.

Also [globalFunctions.cpp](https://github.com/jpcima/fmcomposer/blob/master/src/globalFunctions.cpp#L382) cannot `mkdir` because it has a `~`. It worked when replaced with `/home/user`

I also tried to do this to check if it exists:
```
if (0 != mkdir(appconfigdir.c_str(),0733)) {
  perror("mkdir");
}
```

**Comment by jpcima** [comment]
fixed in 5fdccec225d902bff2a1b0d47620c8f7e38a969e
