### ISSUE TITLE
Segfault when clicking grey bar under presets in settings.

### ISSUE THREAD

**Issue by rambit** [jpcima/fmcomposer#3]
![grey-bar](https://user-images.githubusercontent.com/6752466/74609653-68dc6680-50ec-11ea-886d-342f3c3f05fc.png)

On the settings page, in linux appears a grey bar under the presets, that doesn't appear on Windows. Clicking it causes segmentation fault. But it shouldn't be there?

**Comment by jpcima** [comment]
This is supposed to be a selection of language. It crashes because the list is empty.

Fixed in latest
